import type { CSSProperties } from 'react'

export const editableRootStyle = {
  // Dark luxury editorial palette — warm near-black with gold accent
  '--slot4-page-bg': '#0A0806',
  '--slot4-page-text': '#F0EDE7',
  '--slot4-panel-bg': '#141210',
  '--slot4-surface-bg': '#1C1916',
  '--slot4-muted-text': '#9A9490',
  '--slot4-soft-muted-text': '#6E6A66',
  '--slot4-accent': '#C9A864',
  '--slot4-accent-fill': '#C9A864',
  '--slot4-accent-soft': 'rgba(201,168,100,0.12)',
  '--slot4-on-accent': '#0A0806',
  '--slot4-dark-bg': '#070504',
  '--slot4-dark-text': '#F0EDE7',
  '--slot4-media-bg': '#2A2420',
  '--slot4-cream': '#141210',
  '--slot4-warm': '#111010',
  '--slot4-lavender': '#1C1916',
  '--slot4-gray': '#141210',
  '--slot4-body-gradient': 'none',
  '--editable-page-bg': '#0A0806',
  '--editable-page-text': '#F0EDE7',
  '--editable-container': '1500px',
  '--editable-border': 'rgba(240,237,231,0.10)',
  '--editable-nav-bg': 'transparent',
  '--editable-nav-text': '#F0EDE7',
  '--editable-nav-active': '#C9A864',
  '--editable-nav-active-text': '#C9A864',
  '--editable-cta-bg': '#C9A864',
  '--editable-cta-text': '#0A0806',
  '--editable-search-bg': 'rgba(240,237,231,0.07)',
  '--editable-footer-bg': '#070504',
  '--editable-footer-text': '#F0EDE7',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_2px_8px_rgba(0,0,0,0.5)]',
  shadowStrong: 'shadow-[0_8px_32px_rgba(0,0,0,0.7)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(10,8,6,0.02),rgba(10,8,6,0.85))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8',
    sectionY: 'py-14 sm:py-16 lg:py-20',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[240px] shrink-0 snap-start sm:w-[270px]',
  },
  type: {
    eyebrow: 'text-[10px] font-medium uppercase tracking-[0.38em] text-[var(--slot4-accent)]',
    heroTitle: 'editable-display text-[clamp(48px,8vw,120px)] font-light italic leading-[0.9] tracking-[0.01em]',
    sectionTitle: 'editable-display text-3xl font-light italic tracking-[0.01em] sm:text-4xl',
    body: 'text-[15px] leading-7',
  },
  surface: {
    card: `border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 border border-[var(--slot4-accent)] bg-[var(--slot4-accent-fill)] px-7 py-3 text-[11px] font-medium uppercase tracking-[0.28em] text-[var(--slot4-on-accent)] transition duration-300 hover:opacity-90`,
    secondary: `inline-flex items-center justify-center gap-2 border border-[var(--editable-border)] px-7 py-3 text-[11px] font-medium uppercase tracking-[0.28em] text-[var(--slot4-muted-text)] transition duration-300 hover:border-[var(--slot4-accent)]/50 hover:text-[var(--slot4-page-text)]`,
    accent: `inline-flex items-center justify-center gap-2 ${editablePalette.accentBg} px-7 py-3 text-[11px] font-medium uppercase tracking-[0.28em] text-[var(--slot4-on-accent)] transition duration-300 hover:opacity-90`,
  },
  media: {
    frame: `relative overflow-hidden ${editablePalette.mediaBg}`,
    ratio: 'aspect-[3/4]',
  },
  motion: {
    lift: 'transition duration-500 hover:-translate-y-px hover:shadow-[0_20px_56px_rgba(0,0,0,0.6)]',
    fade: 'transition duration-300 hover:opacity-75',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use wide readable grids; never create skinny columns for paragraphs or cards.',
  'Use horizontal rails for dense post browsing.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
